import BigNumber from 'bignumber.js'


// URLS
export const YEARN_API = 'https://api.yearn.tools/'
export const GAS_PRICE_API = 'https://gasprice.poa.network/'
export const ETHERSCAN_URL = 'https://etherscan.io/'
export const COVER_API = 'https://api.coverprotocol.com/protocol_data/production'


// GENERAL
export const ERROR = 'ERROR'
export const STORE_UPDATED = 'STORE_UPDATED'
export const TX_SUBMITTED = 'TX_SUBMITTED'

export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED'
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED'
export const CONNECT_WALLET = 'CONNECT_WALLET'

export const CONFIGURE = 'CONFIGURE'
export const CONFIGURE_RETURNED = 'CONFIGURE_RETURNED'

export const ACCOUNT_CONFIGURED = 'ACCOUNT_CONFIGURED'
export const ACCOUNT_CHANGED = 'ACCOUNT_CHANGED'


export const CONFIGURE_VAULTS = 'CONFIGURE_VAULTS'
export const VAULTS_CONFIGURED = 'VAULTS_CONFIGURED'

export const CONFIGURE_LENDING = 'CONFIGURE_LENDING'
export const LENDING_CONFIGURED = 'LENDING_CONFIGURED'

export const CONFIGURE_COVER = 'CONFIGURE_COVER'
export const COVER_CONFIGURED = 'COVER_CONFIGURED'

export const GET_GAS_PRICES = 'GET_GAS_PRICES'
export const GAS_PRICES_RETURNED = 'GAS_PRICES_RETURNED'


// VAULTS
export const VAULTS_UPDATED = 'VAULTS_UPDATED'

export const GET_VAULT_BALANCES = 'GET_VAULT_BALANCES'
export const VAULT_BALANCES_RETURNED = 'VAULT_BALANCES_RETURNED'

export const GET_VAULT_PERFORMANCE = 'GET_VAULT_PERFORMANCE'
export const VAULT_PERFORMANCE_RETURNED = 'VAULT_PERFORMANCE_RETURNED'

export const DEPOSIT_VAULT = 'DEPOSIT_VAULT'
export const DEPOSIT_VAULT_RETURNED = 'DEPOSIT_VAULT_RETURNED'

export const APPROVE_VAULT = 'APPROVE_VAULT'
export const APPROVE_VAULT_RETURNED = 'APPROVE_VAULT_RETURNED'

export const WITHDRAW_VAULT = 'WITHDRAW_VAULT'
export const WITHDRAW_VAULT_RETURNED = 'WITHDRAW_VAULT_RETURNED'

export const GET_VAULT_TRANSACTIONS = 'GET_VAULT_TRANSACTIONS'
export const VAULT_TRANSACTIONS_RETURNED = 'VAULT_TRANSACTIONS_RETURNED'

// ACCOUNT
export const GET_ACCOUNT_BALANCES = 'GET_ACCOUNT_BALANCES'
export const ACCOUNT_BALANCES_RETURNED = 'ACCOUNT_BALANCES_RETURNED'



//COVER
export const COVER_UPDATED = 'COVER_UPDATED'

export const GET_COVER_BALANCES = 'GET_COVER_BALANCES'
export const COVER_BALANCES_RETURNED = 'COVER_BALANCES_RETURNED'

export const APPROVE_COVER = 'APPROVE_COVER'
export const APPROVE_COVER_RETURNED = 'APPROVE_COVER_RETURNED'

export const BUY_COVER = 'BUY_COVER'
export const BUY_COVER_RETURNED = 'BUY_COVER_RETURNED'

export const SELL_COVER = 'SELL_COVER'
export const SELL_COVER_RETURNED = 'SELL_COVER_RETURNED'

export const MAX_UINT256 = new BigNumber(2)
  .pow(256)
  .minus(1)
  .toFixed(0);
