export default [{
	"address": "0xD533a949740bb3306d119CC777fa900bA034cd52",
	"symbol": "CRV",
	"decimals": 18,
	"description": "Similar to Uniswap, Curve Finance is an Automated Market Maker (AMM) based Decentralised Exchange (DEX). Unlike Uniswap, its main focus is only to swap between assets that are supposed to have the same value. This is useful in the DeFi ecosystem as there are plenty of wrapped tokens and synthetic tokens that aim to mimic the price of the real underlying asset. \r\n\r\nFor example, one of the biggest pools is 3CRV, which is a stablecoin pool consisting of DAI, USDT, and USDC. Their ratio in the pool will be based on the supply and demand of the market. Depositing a coin with a lesser ratio will yield the user a higher percentage of the pool. As such when the ratio is heavily tilted to one of the coins, it may serve as a good chance to arbitrage.\r\n\r\nCurve Finance also supports yield-bearing tokens. For example, it collaborated with Yearn Finance to release yUSD pools that consisted of yDAI, yUSDT, yUSDC and yTUSD. Users that participated in this pool will not only have yield from the underlying yield-bearing tokens, but also the swap fees generated by the Curve pool. Including the yield farming rewards in terms of CRV tokens, liquidity providers of the pool actually have three sources of yield. ",
}, {
	"address": "0xA64BD6C70Cb9051F6A9ba1F163Fdc07E0DfB5F84",
	"symbol": "aLINK",
	"decimals": 18,
	"description": "Aave LINK is an interest bearing token minted upon deposit and burned when redeemed. The aLINK is pegged 1:1 to the value of the underlying LINK that is deposited in Aave protocol. aLINK, can be freely stored, transferred, and traded. While the underlying asset is loaned out to borrowers, aLINK accrue interest in real time, directly in your wallet!",
}, {
	"address": "0x514910771AF9Ca656af840dff83E8264EcF986CA",
	"symbol": "LINK",
	"decimals": 18,
	"description": "Chainlink is a decentralized oracle service, the first of its kind. When <a href=\"https://www.coingecko.com/en/coins/ethereum\">Ethereum</a> went live in 2015, it revolutionized what blockchain could bring to enterprise solution and traditional business. Blockchain was no longer just a medium for new age financial transaction, confined to <a href=\"https://www.coingecko.com/en/coins/bitcoin\">Bitcoin’s</a> potential to disrupt traditional currency exchange. With Ethereum powered smart contracts, Vitalik Buterin opened up a Pandora’s Box of use cases for blockchain technology. Problem is, per their design, smart contracts can only manage data on the blockchain. Their potential, the ability to provide tamperproof, decentralized applications for uses the world over, is still largely untapped, as many of the smart contract programs built on Ethereum lack a bridge to the real world industries they’re trying to improve.\r\n\r\nChainlink’s first component consists of on-chain contracts deployed on Ethereum’s blockchain.  These oracle contracts process the data requests of users looking to take advantage of the network’s oracle services. If a user or entity wants access to off-chain data, they submit a user contract (or requesting contract) to Chainlink’s network, and the blockchain processes these requests into their own contracts. These contracts are responsible for matching the requesting contract up with the appropriate oracles. The contracts include a reputation contract, an order-matching contract, and an aggregating contract. The first of these, the reputation contract, is exactly as it sounds: it checks an oracle provider’s track record to verify its integrity. In turn, the order-matching contract logs the user contract’s service level agreement on the network and collects bids from responsible oracle providers. Finally, the aggregating contract accumulates the collective data of the chosen oracles and balances them to find the most accurate result.\r\n\r\nUnfortunately, the Chainlink team does not offer a roadmap, but a testnet of Chainlink’s services should come sometime within Q1 of 2018. Generally, the project’s general lack of marketing and concrete updates have frustrated community members in the past. Sergey Nazarov, the project’s CEO, is known for a quiet community presence that favors of behind-the-scenes work on Chainlink. The team may not hype their project much, but for what it’s worth, they sacrifice brand marketing in favor of product development–and some community members find this focus to be refreshing. For instance, they’ve established an oracle with Swift Bank, and have a few quiet partnerships with zepplin_os and Request Network.\r\n\r\nChainlink has the potential to connect smart contracts with the outside world. It may allow parties to smart contracts to be able to receive external inputs that prove performance and create payment outputs that end users want to receive, such as bank payments. This has the potential to allow smart contract to mimic the vast majority of financial agreements currently available in the market. With the Chainlink Network, anyone can securely provide smart contracts with access to key external data and any other API capabilities, in exchange for financial reward. Although it remains to be seen how the incentive system will operate, there is potential for rewards similar to those available for crypto miners to be available to Node Operators that provide useful data to the Chainlink network.\"\r\n\r\nCheck out <a href=\"https://www.coinbureau.com/review/chainlink-link/\">CoinBureau</a> for the complete review on Chainlink.",
}, {
	"address": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
	"symbol": "USDC",
	"decimals": 6,
	"description": "USDC is a fully collateralized US dollar stablecoin. USDC is the bridge between dollars and trading on cryptocurrency exchanges. The technology behind CENTRE makes it possible to exchange value between people, businesses and financial institutions just like email between mail services and texts between SMS providers. We believe by removing artificial economic borders, we can create a more inclusive global economy. ",
}, {
	"address": "0xdF5e0e81Dff6FAF3A7e52BA697820c5e32D806A8",
	"symbol": "yDAI+yUSDC+yUSDT+yTUSD",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x16de59092dAE5CcF4A1E6439D611fd0653f0Bd01",
	"symbol": "yDAI",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x6B175474E89094C44Da98b954EedeAC495271d0F",
	"symbol": "DAI",
	"decimals": 18,
	"description": "MakerDAO has launched Multi-collateral DAI (MCD). This token refers to the new DAI that is collaterized by multiple assets.\r\n",
}, {
	"address": "0xd6aD7a6750A7593E092a9B218d66C0A814a3436e",
	"symbol": "yUSDC",
	"decimals": 6,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x83f798e925BcD4017Eb265844FDDAbb448f1707D",
	"symbol": "yUSDT",
	"decimals": 6,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xdAC17F958D2ee523a2206206994597C13D831ec7",
	"symbol": "USDT",
	"decimals": 6,
	"description": "Tether (USDT) is a cryptocurrency with a value meant to mirror the value of the U.S. dollar. The idea was to create a stable cryptocurrency that can be used like digital dollars. Coins that serve this purpose of being a stable dollar substitute are called “stable coins.” Tether is the most popular stable coin and even acts as a dollar replacement on many popular exchanges! According to their site, Tether converts cash into digital currency, to anchor or “tether” the value of the coin to the price of national currencies like the US dollar, the Euro, and the Yen. Like other cryptos it uses blockchain. Unlike other cryptos, it is [according to the official Tether site] “100% backed by USD” (USD is held in reserve). The primary use of Tether is that it offers some stability to the otherwise volatile crypto space and offers liquidity to exchanges who can’t deal in dollars and with banks (for example to the sometimes controversial but leading exchange <a href=\"https://www.coingecko.com/en/exchanges/bitfinex\">Bitfinex</a>).\r\n\r\nThe digital coins are issued by a company called Tether Limited that is governed by the laws of the British Virgin Islands, according to the legal part of its website. It is incorporated in Hong Kong. It has emerged that Jan Ludovicus van der Velde is the CEO of cryptocurrency exchange Bitfinex, which has been accused of being involved in the price manipulation of bitcoin, as well as tether. Many people trading on exchanges, including Bitfinex, will use tether to buy other cryptocurrencies like bitcoin. Tether Limited argues that using this method to buy virtual currencies allows users to move fiat in and out of an exchange more quickly and cheaply. Also, exchanges typically have rocky relationships with banks, and using Tether is a way to circumvent that.\r\n\r\nUSDT is fairly simple to use. Once on exchanges like <a href=\"https://www.coingecko.com/en/exchanges/poloniex\">Poloniex</a> or Bittrex, it can be used to purchase Bitcoin and other cryptocurrencies. It can be easily transferred from an exchange to any Omni Layer enabled wallet. Tether has no transaction fees, although external wallets and exchanges may charge one. In order to convert USDT to USD and vise versa through the Tether.to Platform, users must pay a small fee. Buying and selling Tether for Bitcoin can be done through a variety of exchanges like the ones mentioned previously or through the Tether.to platform, which also allows the conversion between USD to and from your bank account.",
}, {
	"address": "0x73a052500105205d34Daf004eAb301916DA8190f",
	"symbol": "yTUSD",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x0000000000085d4780B73119b644AE5ecd22b376",
	"symbol": "TUSD",
	"decimals": 18,
	"description": "TrueUSD provides its token holders regular attestations of escrowed balances, full collateral, and also the legal protection against misappropriating underlying USD. The team believes that TrueUSD will be able to come up with the stable trading instrument for the traders of cryptocurrency that has been long-awaited. This will allow the businesses and consumers to use the digital currency as a medium of an exchange. The goal of the TrueUSD team was to build a coin that is stable and which can be used and trusted by them too. TrustToken is a platform that creates the tokens backed by assets that can easily be purchased and sold all around the world. The first asset token of TrustToken is TrueUSD, which is a stable coin and can be redeemed 1-for-1 for US dollars. TrustToken have partnered with registered fiduciaries and banks for holding the funds securely backed by TrueUSD tokens. To increase the amount of security, fiduciaries, and banks directly handle all the funds. Escrowed funds do not give access to the TrueUSD system.\r\n\r\nTrueUSD works with various trust companies which already manage around billions of dollars. Just pass an AML/KYC check, send USD to a trust company with an agreement of escrow. When the funds get verified, their API tells the smart contract of TUSD to mint an equal amount of TUSD to your public <a href=\"https://www.coingecko.com/en/coins/ethereum\">Ethereum</a> address.\r\n\r\nThe USD funds are regularly verified in scheduled attestations by a very much trusted auditing firm. USD funds are kept safely in a third party account, that is escrow accounts, wherein TrustToken does not hold any direct access to the funds and cannot abscond with them even if they wish to. The token burning and minting system makes sure that every TUSD token is backed by 1 USD.\r\n\r\nA mandatory check of AML/KYC makes sure that TUSD keeps shady people away from the entire project. TUSD makes faster transactions in low transaction fees. Even though TUSD is a unique offering, it is most likely overshadowed by its bigger competitors - Tether. While TUSD arguably offers more security and features, it may be losing the marketing battle. This is not to say that the situation will remain the same. With more crypto investors joining the market every day, the good times for TUSD may be on their way.",
}, {
	"address": "0x0bc529c00C6401aEF6D220BE8C6Ea1667F6Ad93e",
	"symbol": "YFI",
	"decimals": 18,
	"description": "Yearn Finance is a suite of products in Decentralized Finance (DeFi) that provides lending aggregation, yield generation, and insurance on the Ethereum blockchain. The protocol is maintained by various independent developers and is governed by YFI holders.\r\n\r\nIt started out as a passion project by Andre Cronje to automate the process of switching capital between lending platforms in search of the best yield offered, as the lending yield is a floating rate rather than fixed rate. Funds are shifted between dYdX, AAVE, and Compound automatically as interest rates change between these protocols. \r\n\r\nThe service offered includes major USD tokens such as DAI, USDT, USDC, and TUSD. For example, if a user deposits DAI into yearn.finance, the user will receive yDAI token in return, which is a yield-bearing DAI token. \r\n\r\nLater on, it collaborated with Curve Finance to release a yield-bearing USD tokens pool that includes four y-tokens: yDAI, yUSDT, yUSDC and yTUSD, it is named as yUSD. \r\n\r\nYearn Finance debuted the vault feature after its token launch, igniting a frenzy on automated yield farming and is considered the initiator of the category of yield farming aggregator. Basically, the vault will help users to claim yield farming rewards and sell it for the underlying assets. \r\n\r\nVaults benefit users by socializing gas costs, automating the yield generation and rebalancing process, and automatically shifting capital as opportunities arise. End users also do not need to have proficient knowledge of the underlying protocols involved or DeFi, thus the Vaults represent a passive-investing strategy. It is akin to a crypto hedge fund where the aim is to increase the amount of assets that users deposited.\r\n\r\n\r\n\r\n",
}, {
	"address": "0x3B3Ac5386837Dc563660FB6a0937DFAa5924333B",
	"symbol": "yDAI+yUSDC+yUSDT+yBUSD",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xC2cB1040220768554cf699b0d863A3cd4324ce32",
	"symbol": "yDAI",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x26EA744E5B887E5205727f55dFBE8685e3b21951",
	"symbol": "yUSDC",
	"decimals": 6,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xE6354ed5bC4b393a5Aad09f21c46E101e692d447",
	"symbol": "yUSDT",
	"decimals": 6,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x04bC0Ab673d88aE9dbC9DA2380cB6B79C4BCa9aE",
	"symbol": "yBUSD",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x4Fabb145d64652a948d72533023f6E7A623C7C53",
	"symbol": "BUSD",
	"decimals": 18,
	"description": "Binance USD (BUSD) is a stable coin pegged to USD that has received approval from the New York State Department of Financial Services (NYDFS). BUSD will be available for direct purchase and redemption at a rate of 1 BUSD = 1 USD. ",
}, {
	"address": "0x075b1bb99792c9E1041bA13afEf80C91a1e70fB3",
	"symbol": "crvRenWSBTC",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xEB4C2781e4ebA804CE9a9803C67d0893436bB27D",
	"symbol": "renBTC",
	"decimals": 8,
	"description": "REN Tokenized BTC\r\n\r\nOnce an asset is in the custody of RenVM, an ERC20 token at a 1:1 value is minted on Ethereum - this can then be used as any ERC20 can within the Ethereum ecosystem (for example, swaps, collateralization, trades etc.)",
}, {
	"address": "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599",
	"symbol": "WBTC",
	"decimals": 8,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xfE18be6b3Bd88A2D2A7f928d00292E7a9963CfC6",
	"symbol": "sBTC",
	"decimals": 18,
	"description": "sBTC or synthetic BTC is a synthetic asset launched by Synthetix Exchange. sBTC mirrors and tracks the price of Bitcoin provided by an oracle - Chainlink.",
}, {
	"address": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
	"symbol": "WETH",
	"decimals": 18,
	"description": "W-ETH is \"wrapped ETH\" but let's start by introducing the players. First, there's Ether token. Ether or ETH is the native currency built on the Ethereum blockchain.\r\nSecond, there are alt tokens. When a dApp (decentralized app) is built off of the Ethereum Blockchain it usually implements it’s own form of Token. Think Augur’s REP Token, or Bancor's BNT Token. Finally the ERC-20 standard. ERC20 is a standard developed after the release of ETH that defines how tokens are transferred and how to keep a consistent record of those transfers among tokens in the Ethereum Network.",
}, {
	"address": "0x6c3F90f043a72FA612cbac8115EE7e52BDe6E490",
	"symbol": "3Crv",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x056Fd409E1d7A124BD7017459dFEa2F387b6d5Cd",
	"symbol": "GUSD",
	"decimals": 2,
	"description": "The Gemini dollar — the world’s first regulated stablecoin — combines the creditworthiness and price stability of the U.S. dollar with blockchain technology and the oversight of U.S. regulators.\r\n\r\nGet Gemini dollars 1-to-1 for U.S. dollars on Gemini.\r\nGemini dollars can be used on the Ethereum network.\r\n\r\nISSUER\r\nThe Gemini dollar is issued by Gemini Trust Company, LLC, a New York trust company.\r\n\r\nBANK\r\nU.S. dollars that correspond to the Gemini dollars issued and in circulation are held at a U.S. bank and eligible for FDIC “pass-through” deposit insurance, subject to applicable limitations.\r\n\r\nEXAMINATION\r\nThe U.S. dollar deposit balance is examined monthly by an independent registered public accounting firm to verify the 1:1 peg. All Independent Accountants’ Reports are published and available <a href=\"https://gemini.com/dollar/#reports\">here</a>.\r\n\r\nSECURITY AUDIT\r\nThe Gemini dollar is a cryptographic token built on the Ethereum Network according to the ERC20 standard for tokens. The code of the Gemini dollar smart contracts has been audited by Trail of Bits, Inc., an information security research & development firm, whose report is publicly available <a href=\"https://gemini.com/wp-content/themes/gemini/assets/img/dollar/gemini-dollar-trailofbits-audit.pdf\">here</a>.\r\n\r\nGemini was founded four years ago with a mission: build a bridge to the future of money. Gemini dollar aims to combine creditworthiness and price stability of the U.S. dollar with blockchain and the oversight of U.S. regulators, the New York State Department of Financial Service.\r\n\r\nGemini dollar is a stable value coin that is:\r\n\r\n1. issued by Gemini, a New York trust company\r\n2. strictly pegged 1:1 to the U.S. dollar\r\n3. built on Ethereum network according to ERC20 token standards\r\n\r\nStarting 10th September 2018, you will be able to convert U.S. dollars in your Gemini account into Gemini dollars and withdraw them to an Ethereum address. You will also be able to automatically convert GUSD back as USD into your Gemini account. GUSD is expected to be listed on Bibox soon.",
}, {
	"address": "0x845838DF265Dcd2c412A1Dc9e959c7d08537f8a2",
	"symbol": "cDAI+cUSDC",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643",
	"symbol": "cDAI",
	"decimals": 8,
	"description": "Compound protocol balance token",
}, {
	"address": "0x39AA39c021dfbaE8faC545936693aC917d5E7563",
	"symbol": "cUSDC",
	"decimals": 8,
	"description": "Compound is an open-source, autonomous protocol built for developers, to unlock a universe of new financial applications. Interest and borrowing, for the open financial system.",
}, {
	"address": "0x1AEf73d49Dedc4b1778d0706583995958Dc862e6",
	"symbol": "musd3CRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xD2967f45c4f384DEEa880F807Be904762a3DeA07",
	"symbol": "gusd3CRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x194eBd173F6cDacE046C53eACcE9B953F28411d1",
	"symbol": "eursCRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xe2f2a5C287993345a840Db3B0845fbC70f5935a5",
	"symbol": "mUSD",
	"decimals": 18,
	"description": "MUSD is decentralized peer-to-peer, based on Ethereum blockchain.\r\nShop and pay your services and products using MUSD.\r\nAnyone who owns MUSD will find a variety of fields to use them, not only trading and exchanges but also it can be use to shop and pay your services and products.",
}, {
	"address": "0x49849C98ae39Fff122806C06791Fa73784FB3675",
	"symbol": "crvRenWBTC",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x4f3E8F405CF5aFC05D68142F3783bDfE13811522",
	"symbol": "usdn3CRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x94e131324b6054c0D789b190b2dAC504e4361b53",
	"symbol": "ust3CRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x410e3E86ef427e30B9235497143881f717d93c2A",
	"symbol": "bBTC/sbtcCRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x64eda51d3Ad40D56b9dFc5554E06F94e1Dd786Fd",
	"symbol": "tbtc/sbtcCrv",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x2fE94ea3d5d4a175184081439753DE15AeF9d614",
	"symbol": "oBTC/sbtcCRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xDE5331AC4B3630f94853Ff322B66407e0D6331E8",
	"symbol": "pBTC/sbtcCRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xb19059ebb43466C323583928285a49f558E572Fd",
	"symbol": "hCRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xC25a3A3b969415c80451098fa907EC722572917F",
	"symbol": "crvPlain3andSUSD",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x57Ab1ec28D129707052df4dF418D58a2D46d5f51",
	"symbol": "sUSD",
	"decimals": 18,
	"description": "sUSD, or synthetic USD, is a synthetic asset launched by Synthetix Exchange. sUSD mirrors and tracks the price of USD provided by an oracle - Chainlink.",
}, {
	"address": "0x5B5CFE992AdAC0C9D48E05854B2d91C73a003858",
	"symbol": "husd3CRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x3a664Ab939FD8482048609f652f9a0B0677337B9",
	"symbol": "dusd3CRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xFd2a8fA60Abd58Efe3EeE34dd494cD491dC14900",
	"symbol": "a3CRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xaA17A236F2bAdc98DDc0Cf999AbB47D47Fc0A6Cf",
	"symbol": "ankrCRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x02d341CcB60fAaf662bC0554d13778015d1b285C",
	"symbol": "saCRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x7Eb40E450b9655f4B3cC4259BCC731c63ff55ae6",
	"symbol": "usdp3CRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xcee60cFa923170e4f8204AE08B4fA6A3F5656F3a",
	"symbol": "linkCRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x06325440D014e39736583c165C2963BA99fAf14E",
	"symbol": "steCRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xA3D87FffcE63B53E0d54fAa1cc983B7eB0b74A9c",
	"symbol": "eCRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x111111111117dC0aa78b770fA6A738034120C302",
	"symbol": "1INCH",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x5282a4eF67D9C33135340fB3289cc1711c13638C",
	"symbol": "ib3CRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xc5bDdf9843308380375a611c18B50Fb9341f502A",
	"symbol": "yveCRV-DAO",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xEd279fDD11cA84bEef15AF5D39BB4d4bEE23F0cA",
	"symbol": "LUSD3CRV-f",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xd632f22692FaC7611d2AA1C0D552930D43CAEd3B",
	"symbol": "FRAX3CRV-f",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984",
	"symbol": "UNI",
	"decimals": 18,
	"description": "UNI is committed to building a non-probable cross-chain hub, and its unique TPOS➕RAFT multi-function consensus algorithm implements user account management, cross-chain asset flashing, multi-chain wallet management, and one-click flash multi-chain assets; The cross-chain interface service system Phoenix enters the application environment of the cross-chain service through the RPC remote call protocol; the UNI platform will provide an optimized smart contract library to reduce the difficulty of developing DAPP, enabling the local and third-party DAPP ecosystem to rapidly expand and more Fast improvement; at the same time, using IPFS technology, HDFS distributed storage and big data AI algorithm to provide basic services such as data storage and big data artificial intelligence to the UNI main chain, empowering DApp. UNI will realize the free flow of assets between different chains, release the potential of different chains, allow more users to participate, and enable more chains to connect, eventually forming a truly big ecology, a network of inter-connected blockchains.",
}, {
	"address": "0xEcd5e75AFb02eFa118AF914515D6521aaBd189F1",
	"symbol": "TUSD3CRV-f",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x4807862AA8b2bF68830e4C8dc86D0e9A998e085a",
	"symbol": "BUSD3CRV-f",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F",
	"symbol": "SNX",
	"decimals": 18,
	"description": "Synthetix is based in Australia, Synthetix launched a seed funding round in September, 2017 to develop the concept of a self-contained stablecoin payment network. They then kicked off their public ICO on February 28, 2018 and by the end of the ICO on March 7, 2018, they had met their goal of $30,000,000 USD. Synthetix was <a href=\"https://blog.havven.io/havven-is-transforming-into-synthetix-2fdf727b8892\">rebranded</a> from Havven on November 30, 2018.\r\n\r\nSynthetix is led by a multidisciplinary team of 13 individuals. The project was founded by Kain Warwick, who previously co-founded blueshyft, one of the largest digital payment networks in Australia. The CTO is Justin Moses, who also serves as the Director of Engineering at MongoDB. Synthetix aims to address the problem that companies running centralized payment networks such as PayPal, credit card networks, or the SWIFT banking network have “absolute control over the value within the network, so any transaction conducted within them may be blocked or reversed at any time.” According to the Synthetix white paper, “Although this is ostensibly designed to protect users, it introduces systemic risk for all participants. If the network is compromised or its owners cease to behave benevolently, no party can trust that the value in their account is secure or accessible.”\r\n\r\nThis is theorized to work because anyone who holds SNX tokens in escrow will be incentivized by Synthetix rewards derived from network transaction fees that will be distributed “in proportion with how well each issuer maintains the correct Synths supply.” When a Synthetix escrow user puts their SNX in escrow, USD-stabilized Synths will be automatically put up for sale on a decentralized exchange at a price of $1 USD. To release escrowed SNX, the user must buy back the Synths issued (also at a price of $1 USD) at which point the Synths will be burned. The Synthetix system uses an algorithm to adjust network fees, and therefore dividends, to SNX holders to incentivize (or disincentivize) the holding of SNX in escrow smart contracts, and thus, the creation of Synths. The theory is that this will cause users to mint and burn Synths in the appropriate amount based solely on supply and demand.",
}, {
	"address": "0x43b4FdFD4Ff969587185cDB6f0BD875c5Fc83f8c",
	"symbol": "alUSD3CRV-f",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x53a901d48795C58f485cBB38df08FA96a24669D5",
	"symbol": "rCRV",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0x03ab458634910AaD20eF5f1C8ee96F1D6ac54919",
	"symbol": "RAI",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}, {
	"address": "0xcA3d75aC011BF5aD07a98d02f18225F9bD9A6BDF",
	"symbol": "crvTricrypto",
	"decimals": 18,
	"description": "I don't have a description for this asset at this moment.",
}]
